version: '3'
services: 
   postgres: 
      image: "postgres:13.2"
      ports: 
         - "5432.5432"
      environment:
        POSTGRES_USERS: "sowmyakl"
        #only use that locally or in CI/CD
        POSTGRES_HOS_AUTH_METHOD: trust
        POSTGRES_DB: "new"
